### ISSUE TITLE
how to find these workload files?

### ISSUE THREAD

**Issue by NihaoyaLeolar** [Chrisys93/IcarusRepoSEND#2]
The config at /examples/repos-mgmt/config1_trace.py need some workload files to gererate requests.
But I don't now how to find it or where to download it.
![image](https://user-images.githubusercontent.com/59057703/145771092-8561ed33-3eb8-4baa-b624-bf8e5c95acd2.png)

Thanks you.

**Comment by Chrisys93** [comment]
Use one of the synthetic-generated datasets. You can then learn how to use your own datasets. https://github.com/Chrisys93/IcarusRepoSEND/tree/master/examples/repos-mgmt
